// eventsData.ts
export interface EventItem {
  year: string;
  event: string;
}

export const EVENTS: EventItem[] = [
  // Easy Events (30)
  { year: "1210", event: "Mickey Mouse becomes king" },
  { year: "1365", event: "SpongeBob opens first burger shop" },
  { year: "1441", event: "Pikachu learns to speak" },
  { year: "1502", event: "Winnie the Pooh finds golden honey" },
  { year: "1616", event: "Tom and Jerry become friends" },
  { year: "1701", event: "Doraemon invents candy clouds" },
  { year: "1744", event: "Scooby Doo solves first mystery" },
  { year: "1820", event: "Pokemon school opens" },
  { year: "1862", event: "Sonic wins running race" },
  { year: "1915", event: "Mario saves princess first time" },
  { year: "1944", event: "Donald Duck becomes teacher" },
  { year: "1965", event: "Batman builds candy cave" },
  { year: "1983", event: "Care Bears paint the rainbow" },
  { year: "1999", event: "Teletubbies find magic wand" },
  { year: "2010", event: "Peppa Pig discovers chocolate rain" },
  { year: "1222", event: "Barbie becomes astronaut" },
  { year: "1355", event: "Blue's Clues solves biggest puzzle" },
  { year: "1466", event: "Power Rangers open dance school" },
  { year: "1523", event: "Ninja Turtles find golden pizza" },
  { year: "1633", event: "Bugs Bunny plants magic carrots" },
  { year: "1766", event: "Dora explores candy mountain" },
  { year: "1809", event: "Garfield declares Mondays fun" },
  { year: "1888", event: "Tweety Bird becomes detective" },
  { year: "1921", event: "Hello Kitty opens first café" },
  { year: "1977", event: "Popeye discovers sweet spinach" },
  { year: "2001", event: "Shrek's swamp turns to chocolate" },
  { year: "2016", event: "Elsa builds ice cream castle" },
  { year: "2022", event: "PAW Patrol saves candy factory" },
  { year: "1288", event: "Minions find banana island" },
  { year: "1344", event: "Paddington opens marmalade shop" },

  // Moderate Events (30)
  { year: "1020", event: "Dragon teaches math class" },
  { year: "1187", event: "Unicorn wins Olympic medal" },
  { year: "1390", event: "Flying carpet taxi service starts" },
  { year: "2036", event: "Robot dog becomes president" },
  { year: "1433", event: "Wizards open skateboard park" },
  { year: "1409", event: "Mermaids start singing contest" },
  { year: "1330", event: "Giants join basketball team" },
  { year: "1046", event: "Fairies paint city rainbow" },
  { year: "1272", event: "Cloud castle discovered" },
  { year: "1478", event: "Magic tree grows candy" },
  { year: "1543", event: "Talking books teach dance" },
  { year: "1672", event: "Moon made of cheese confirmed" },
  { year: "2090", event: "Dinosaurs return as pets" },
  { year: "2111", event: "Flying cars run on bubbles" },
  { year: "1155", event: "Time machine sends lunch back" },
  { year: "1249", event: "Singing flowers win talent show" },
  { year: "1321", event: "Pirates find treasure map in pizza" },
  { year: "1400", event: "Animals hold music festival" },
  { year: "1515", event: "Rainbow bridge connects continents" },
  { year: "1599", event: "Magic paintbrush colors ocean" },
  { year: "1690", event: "Stars dance every midnight" },
  { year: "1775", event: "Giant teddy bear becomes mayor" },
  { year: "1933", event: "Ice cream never melts discovery" },
  { year: "1989", event: "Chocolate river flows first time" },
  { year: "2003", event: "Flying fish deliver mail" },
  { year: "2012", event: "Clouds shaped like candy appear" },
  { year: "2025", event: "Toys come alive at museum" },
  { year: "2060", event: "Friendly ghosts open hotel" },
  { year: "2102", event: "Rainbow waterfall discovered" },
  { year: "1080", event: "Magic school bus first flight" },

  // Hard Events (20)
  { year: "1186", event: "Time-traveling pandas arrive" },
  { year: "1577", event: "Invisible castle appears briefly" },
  { year: "1622", event: "Dream machine invented" },
  { year: "1733", event: "Memory borrowing starts" },
  { year: "1844", event: "Constellation plays music" },
  { year: "1957", event: "Gravity goes on vacation" },
  { year: "2028", event: "Thoughts become bubbles" },
  { year: "2045", event: "Wind learns to sing" },
  { year: "2088", event: "Shadow trading begins" },
  { year: "2150", event: "Time starts moving backwards" },
  { year: "888", event: "Mirror world discovered" },
  { year: "1123", event: "Dreams become reality" },
  { year: "1299", event: "Colors gain consciousness" },
  { year: "1455", event: "Imagination becomes visible" },
  { year: "1567", event: "Stories write themselves" },
  { year: "1788", event: "Silence becomes loud" },
  { year: "1899", event: "Light learns to dance" },
  { year: "1967", event: "Echo starts painting" },
  { year: "2055", event: "Numbers refuse to count" },
  { year: "3000", event: "Reality takes a holiday" }
];

